### ISSUE TITLE
Custom Sign In screen

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/eu-tours#43]
Left side of 1920px screen should have illustration, and right side should have all sign in options.

**Comment by nazrul7711** [comment]
hey @anicmarko9  i want to work on this can u give me some what of description how would you want it to look like or what kind of illustration u want in it? any demo sit???

**Comment by anicmarko9** [comment]
![login-1](https://github.com/anicmarko9/eu-tours/assets/73799942/a1ab5a3e-5e68-4f5a-aecc-424a57530ef5)

This image above is on 1920x1080, illustration is on the left, and login on the right. On mobile device, illustration is either non-existent or above login form like "flex-col".
- **Illustration:** [storyset](https://storyset.com/login)
- **GitHub and Google Icons:** [react-icons](https://react-icons.github.io/react-icons)

You don't need to add "or" and "Single Sign-On".

Illustration color should be "#FF6000", and background color of two sign-in buttons shouldn't be light green like in this image above, you can experiment and see what fits best between these colors: 
- primary: "#2B2A4C",
- secondary: "#FF6000",
- tertiary: "#4F4557"

You refer to these options with TailwindCSS like "bg-secondary", they are already implemented in config.
If there isn't any color mixing that looks nice, just use black and white, for an example you can set background color to black and text to white "bg-black text-white".

If you do not know Next.js file structure, just make SignIn.tsx anywhere you like and I will personally implement all backend logic behind that component.
